Add logic to update configMaps on operator
arschles/http-add-on pull request #10
Opened 2021-08-11 19:44 UTC by khaosdoctor

Adds the logic to save the routing tables in the config maps

2021-08-11 21:50 UTC, arschles requested changes
@khaosdoctor left some suggestions. this is a good start. let's get this merged and then I'll go and implement the interceptor side of things.

2021-08-11 21:50 UTC, arschles commented on operator/controllers/routing_table.go
> +	if routingConfigMap == nil { // if the routing table doesn't exist, we need to create it with the latest data
@khaosdoctor can you put the comment above this line?

2021-08-11 21:50 UTC, arschles commented on operator/controllers/routing_table.go
> +	if err != nil { return err }
```suggestion
	if err != nil {
	    return err
	}
```

2021-08-11 21:50 UTC, arschles commented on operator/controllers/routing_table.go
> +	if marshalErr != nil { // should never happen
```suggestion
	if marshalErr != nil {
```

2021-08-11 21:50 UTC, arschles commented on operator/controllers/routing_table.go
> +	lggr logr.Logger,
let's put the `lggr` parameter after `ctx`, to be consistent

```suggestion
	ctx context.Context,
	lggr logr.Logger,
	cl client.Client,
	namespace string,
	table *routing.Table,
```

2021-08-11 21:50 UTC, arschles commented on operator/controllers/routing_table.go
> +		if _, patchErr := k8s.PatchConfigMap(ctx, cl, lggr, routingConfigMap, newRoutingTable); patchErr != nil { return patchErr }
```suggestion
		if _, patchErr := k8s.PatchConfigMap(ctx, cl, lggr, routingConfigMap, newRoutingTable); patchErr != nil {
		    return patchErr
		}
```

2021-08-11 21:50 UTC, arschles commented on pkg/k8s/configMap.go
> +	logger logr.Logger,
let's put the logger next to `ctx` to be consistent

```suggestion
	ctx context.Context,
	logger logr.Logger,
	cl client.Client,
	configMap *corev1.ConfigMap,
```

2021-08-11 21:50 UTC, arschles commented on pkg/k8s/configMap.go
> +	if err == nil { return err }
```suggestion
	if err == nil {
	    return err
	}
```

2021-08-11 21:50 UTC, arschles commented on pkg/k8s/configMap.go
> +	if existentConfigMap.Name != "" { return errors.New("ConfigMap already exists") }
```suggestion
	if existentConfigMap.Name != "" {
	    return fmt.Errorf("ConfigMap %s already exists", configMap.Name)
	}
```

2021-08-11 21:50 UTC, arschles commented on pkg/k8s/configMap.go
> +	if createErr != nil { return createErr }
```suggestion
	if createErr != nil {
	    return createErr
	}
```

2021-08-11 21:50 UTC, arschles commented on pkg/k8s/configMap.go
> +	return nil
```suggestion
	return cl.Delete(ctx, configMap)
```

2021-08-11 21:50 UTC, arschles commented on pkg/k8s/configMap.go
> +
```suggestion
```

2021-08-12 00:01 UTC, arschles commented
@khaosdoctor I think you also will need to delete the "admin" server endpoints in the operator

2021-08-12 16:09 UTC, khaosdoctor commented
@arschles Guess I removed everything. Can you check?

2021-08-12 17:47 UTC, merged